# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowaviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windowaviso(object):
    def setupUi(self, windowaviso):
        windowaviso.setObjectName("windowaviso")
        windowaviso.resize(360, 200)
        windowaviso.setModal(True)
        self.lblmageAviso = QtWidgets.QLabel(windowaviso)
        self.lblmageAviso.setGeometry(QtCore.QRect(120, 40, 91, 51))
        self.lblmageAviso.setText("")
        self.lblmageAviso.setPixmap(QtGui.QPixmap("img/warning.png"))
        self.lblmageAviso.setScaledContents(True)
        self.lblmageAviso.setObjectName("lblmageAviso")
        self.lblAviso = QtWidgets.QLabel(windowaviso)
        self.lblAviso.setGeometry(QtCore.QRect(130, 100, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblAviso.setFont(font)
        self.lblAviso.setObjectName("lblAviso")
        self.btnBoxAviso = QtWidgets.QDialogButtonBox(windowaviso)
        self.btnBoxAviso.setGeometry(QtCore.QRect(90, 140, 156, 23))
        self.btnBoxAviso.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.btnBoxAviso.setObjectName("btnBoxAviso")
        self.btnBoxAviso.accepted.connect(windowaviso.accept)
        self.btnBoxAviso.rejected.connect(windowaviso.reject)

        self.retranslateUi(windowaviso)
        QtCore.QMetaObject.connectSlotsByName(windowaviso)

    def retranslateUi(self, windowaviso):
        _translate = QtCore.QCoreApplication.translate
        windowaviso.setWindowTitle(_translate("windowaviso", "Aviso"))
        self.lblAviso.setText(_translate("windowaviso", "Desea salir?"))
